// <auto-generated />
using System;
using AmorkApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AmorkApp.Migrations
{
    [DbContext(typeof(AmorkDbContext))]
    [Migration("20260206071049_ResetSchema")]
    partial class ResetSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AmorkApp.Data.Food", b =>
                {
                    b.Property<int>("FoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("food_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FoodId"));

                    b.Property<string>("CookingTime")
                        .HasColumnType("text")
                        .HasColumnName("cooking_time")
                        .HasAnnotation("Relational:JsonPropertyName", "cooking_time");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("food_name")
                        .HasAnnotation("Relational:JsonPropertyName", "food_name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.HasKey("FoodId");

                    b.ToTable("foods");
                });

            modelBuilder.Entity("AmorkApp.Data.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email")
                        .HasAnnotation("Relational:JsonPropertyName", "email");

                    b.Property<string>("Fullname")
                        .HasColumnType("text")
                        .HasColumnName("fullname")
                        .HasAnnotation("Relational:JsonPropertyName", "fullname");

                    b.Property<string>("MemberType")
                        .HasColumnType("text")
                        .HasColumnName("member_type")
                        .HasAnnotation("Relational:JsonPropertyName", "memberType");

                    b.Property<string>("PasswordText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_text")
                        .HasAnnotation("Relational:JsonPropertyName", "passwordText");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone")
                        .HasAnnotation("Relational:JsonPropertyName", "phone");

                    b.HasKey("UserId");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
